### ISSUE TITLE
Make a favicon

### ISSUE THREAD

**Issue by TheFireFerret** [cs373gc-fall-2016/interswellar#10]

**Comment by jedyobidan** [comment]
We need a mapping from /favicon.ico to interswellar/static/favicon.ico?

**Comment by TheFireFerret** [comment]
that's a good question

**Comment by jedyobidan** [comment]
How do favicons work?

**Comment by TheFireFerret** [comment]
i want to use this 🌠

**Comment by dshimo** [comment]
ye shooting star looks good
